/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:4dbd03ef-b0e2-4734-a1cb-04d6f3132d2f", 
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_74q6HgfRp",
    "aws_user_pools_web_client_id": "6ckf4mve0c3n7foh1o5h939dsl",
    "oauth": {}
};


export default awsmobile;