/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:ef71bda6-d614-4c88-87f9-2cf98bd6c02d",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_gonQnvgm7",
    "aws_user_pools_web_client_id": "49d0fqnolg68mvneqi6jal5sot",
    "oauth": {}
};


export default awsmobile;
