/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:c3f788a0-3d77-4c1c-80c4-b7897130ba58", 
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_QNoJgH74J",
    "aws_user_pools_web_client_id": "49h8jnq7vn0b05l5h8ck2i4an7",
    "oauth": {}
};


export default awsmobile;